version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile     
    ports:
      - "3000:3000"    
    depends_on:
      - db
    networks:
      - backend

  db:
    build: 
      context: .
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: readEase
    ports:
      - "5432:5432"
    networks:
      - backend
    
networks:
  backend:
    driver: bridge
