version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile     
    ports:
      - "3000:3000"    
    depends_on:
      - redis
    networks:
      - backend

  redis:
    build: 
      context: .
      dockerfile: "Dockerfile redis"    
    ports:
      - "6379:6379"
    networks:
      - backend
    
networks:
  backend:
    driver: bridge
