name: Backend CI/CD

on:
  push:
    branches:
      - '*'

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd backend
        pip3 install --upgrade pip
        pip3 install -q -U google-generativeai
        pip3 install -r requirements.txt

    - name: Run tests
      run: |
        cd backend        
        python services/api_test.py
